name = "Anki 3"
author = "Carl Malmz"
version = "1.2.0"
description = "Private modpack for the Anki 3 server"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dd8d82af5c528e7fa011503fbe1ac98643ebc30c91a07b6f6124255a3f9d9db5"

[versions]
fabric = "0.14.24"
minecraft = "1.20.1"
