name = "Anki 3"
author = "Carl Malmz"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "151ee2abed29fb5f287a607f0b1168b8e4c70fc576de80921d537ebc0b9a02ae"

[versions]
fabric = "0.14.24"
minecraft = "1.20.1"
