name = "Anki 3"
author = "Carl Malmz"
version = "1.1.0"
description = "Private modpack for the Anki 3 server"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "939539f2866694983106f526f070bc2a6f5ae791957301b0b5b271d154254a9d"

[versions]
fabric = "0.14.24"
minecraft = "1.20.1"
